os: linux 
language: python
python:
        - "3.8"
install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p miniconda
        - source "miniconda/etc/profile.d/conda.sh"
        - conda install -n base -y conda=4.5.13
        - conda create -n harmonization -y -c bioconda snakemake blast ariba=2.14.4=py36he1b5a44_0 groot=0.8.3=1
        - conda activate harmonization
        - cd data/dbs
        - bash get_dbs.sh
        - cd ../..
        - cd data/test
        - bash get_test_data.sh
        - cd ../..
script: 
    snakemake --configfile config/config.yaml --use-conda --jobs 1
