# Output and working directory (all other directories below, if not absolute, are relative to this one)
species: "anySpeciesName@edit"

# path or URL to sample sheet (TSV format, columns: sample, assembly); can be created by scripts/create_sampleSheet.sh --mode assembly
samples: "config/test_data.tsv"

params:
  db_dir: "data/dbs"
  threads: 1 #number of threads per rule
  abricate:
    name: "ncbi"
    minid: 75 #minimum identity threshold
    mincov: 0 #minimum coverage threshold
  srst2:
    gene_db: "data/dbs/ResFinder.fasta"
    min_depth: 5
    max_divergence: 10
  ariba:
    #empty, no options exposed
  staramr:
    #empty, no options exposed
  amrfinder:
    organism: "Klebsiella" #must be defined to enable mutation detection: set amrfinder --list_organisms for options
  groot:
    db_source: "resfinder" #which preclustered db to use
    read_length: 100 # readlengh to use for indexing the preclustered db
  rgi:
    db_version: "3.0.7"
  resfams:
    #empty, no options exposed
  mykrobe:
    #todo
  resfinder:
    #empty, no options exposed
  kmerresistance:
    amr_db: "data/dbs/resfinder/resfinder_kma"
    species_db: "data/dbs/resfinder/16S_species"
  srax:
     dbtype: "basic"
  amrplusplus:
    refdb: "data/dbs/megares/megares_drugs_database_v2.00.fasta"
    annots: "data/dbs/megares/megares_drugs_annotations_v2.00.csv" 
    resistome_tool: "data/non_conda_deps/resistomeanalyzer/resistome"
    rarefaction_tool: "data/non_conda_deps/rarefactionanalyzer/rarefaction"
    snp_tool: "data/non_conda_deps/snpfinder/snpfinder"
  SSTAR:
    binary: "data/non_conda_deps/c-SSTAR/c-SSTAR"
    refdb: "data/dbs/ResFinder.fasta"
  pointfinder:
    binary: "data/non_conda_deps/pointfinder/PointFinder.py"
    dbpath: "data/dbs/pointfinder_db" 
    species: "escherichia_coli"
    
